### PR TITLE
Major rewrite

### PR DESCRIPTION
**Pull request by mhmiles**
I changed a ton of stuff to more closely follow the cast spec/sdk. Added a bunch of additional capabilities. Got rid of objc support. Would you ever consider pulling this or should I start as a new project?

### CODE REVIEW

**Comment by insidegui** [comment]
Hi @mhmiles, this looks good! I'm interested in pulling it, but I need some time to evaluate the changes and do some testing. I'll do it this weekend and let you know if I need anything changed.

Thanks!

**Comment by insidegui** [comment]
I'm seeing a crash in `CastMediaStatus.swift` line 44 when trying to load media with the default media player.

**Comment by mhmiles** [comment]
Crash should be fixed. I also added a test cast button in the iOS sample app. Tested to work on my Google Home Mini.

**Comment by insidegui** [comment]
@mhmiles ChromeCastCore was originally created to be used with [WWDC](/insidegui/WWDC), after assessing its current situation and doing a quick poll with users of the app, I noticed it's not a very important feature, but it's a feature I would like to keep in the app for as long as it's feasible.

It also happens to be a dependency of [AppleEvents](/insidegui/AppleEvents), which is written in Objective-C, so support for that language is still important.

I also came to the realization that I'm not interested in providing support for use cases other than my own. For those reasons, I think it's best that you take your work and make it into its own project rather than merging all changes here (which would break both apps mentioned).

Sorry it took me so long to give a definitive answer and thank you for contributing to open-source.

**Comment by mhmiles** [comment]
Sounds good. Thanks Gui. Love the podcast.

**Comment by insidegui** [comment]
If you end up making your own library, make sure to link it here so I can add it to the readme 😉

**Comment by mhmiles** [comment]
I will definitely do that.

**Comment by mhmiles** [comment]
I've released my fork as [OpenCastSwift](https://github.com/mhmiles/opencastswift). Thanks for all your help.

**Comment by insidegui** [comment]
Added to readme 🎉

**Pull request closed without merging**
